name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit=10.1
  - pip=20.0
  - python=3.7
  - pytorch=1.6
  - torchvision=0.7
  - numpy=1.17
  - h5py=2.10.0
  - scipy=1.5.2
  - pandas=1.1
  - pip:
    - dgl-cu101==0.5a200817
    - pyflux==0.4